- evil-collection.el
- evil-doc-view.el
@Ambrevar Looking for some feedback before I push this.
1. C-j/C-k for next/previous page seems reasonable. I think gj/gk are useful too.
Do we want to bind those also?
2. C-u, this replaces the universal argument. It should probably be wrapped in the evil variable wants-c-u (or whatever the name is) but what happens if they change that value after they've set this.
It'd be nice for it to automatically update. Maybe an advice instead? That seems heavy.
3. Opinions on RET for image-next-line?
4. +, 0, - for scaling?
5. I used W for fit width which is a movement from evil but since it's doc-view, that won't be used anyway.
6. H and P are kinda similar to W.
7. The Ctrl-* keys are just taken from the emacs version of the binds.
> Add doc-view

- evil-arc-mode.el
- evil-calendar.el
- evil-dired.el
- evil-info.el
- evil-man.el
- evil-occur.el
- evil-pdf.el
- evil-profiler.el
- evil-transmission.el
- readme.org
This should fix #20 and #27.
Since I don't use all the modes impacted by this change, this requires some extra feedback.
The biggest change is that "o" and "C-o" do not "follow to other window" anymore.  Instead, "o" is for sorting and "C-o" is back to its global binding, `evil-jump-backward`.
> Make sort / follow / select bindings consistent with the rationale

- evil-collection.el
Would be nice if the user could use the custom interface to determine what gets enabled and what doesn't.
> Make evil-collection-mode-list customizable.

- evil-collection-ivy.el
- evil-collection-minibuffer.el
Also consolidate binding location. I think all ivy bindings should go in `evil-collection-ivy`. The insert bindings are because some of evil's bindings override ivy's. (Although, maybe we shouldn't override C-r in insert mode, even in the minibuffer... ?)
> Add more ivy-minibuffer-map bindings

- evil-collection-ibuffer.el
Per [the readme](https://github.com/jojojames/evil-collection#quitting-q-zq-zz), `q` is used for quitting when macros are not useful. Binding `q` to bury buffer is a bad decision since it goes against this philosophy, and there's already a default binding for bury buffer - `b`. Since `b` dosen't make too much sense in ibuffer mode, it makes sense to use this key in evil mode too. 
Let me know if you think differently, while I'm open to binding other keys to bury-buffer, I think `q` should be reserved for quitting to keep the experience seamless.
> Add quit bindings to evil-collection ibuffer

- evil-collection-anaconda-mode.el
I don't know whether `evil-collection` is meant for the stable packages in melpa. If it is, then reject this PR because the current setup is correct. However the latest anaconda-mode on melpa renamed `anaconda-mode-view-mode-map` to `anaconda-view-mode-map`.
> anaconda-mode-view-mode-map doesn't exist; use anaconda-view-mode-map instead

- evil-collection.el
This fixes this message (no space after `evil`):
```
Warning (evil-collection): Make sure to set `evil-want-integration' to nil before loading evilor evil-collection.
```
> Add missing space

- evil-collection-which-key.el
- evil-collection.el
The key "?" can be changed to "h" since it was its default, it will be invoked after "C-h h". "g?" won't work here because of the way which-key is coded. The other possible bindings are commented out.
> Support for which-key

- evil-collection-diff-mode.el
I often see the `Evil Diff: enter motion state` message while using magit and vdiff. Seems to me that these messages were meant for debugging purposes, hence this PR.
Thank you!
> Remove debugs in evil-collection-diff-mode.el

- evil-collection-neotree.el
- evil-collection.el
Added support for neotree-mode. 
* Some keys require revision (e.g. "s,S") some others
like "H,K,L" could be used more. 
* Many keybings do not coincide with
the ones used in spacemacs. 
* `neotree-change-root` could use a better
alternative.
> Neotree mode support

- evil-collection.el
Fix typo, refs https://github.com/jojojames/evil-collection/pull/91#issuecomment-366544730
> evil-collection-delete-operators: fix typo

- evil-collection-daemons.el
- evil-collection.el
This PR adds support for [daemons.el](https://github.com/cbowdon/daemons.el).
This is a very simple binding, simply binding all the default binds to evil as well. I don't think it's a problem because all the bindings correspond to editing commands (which don't make sense in daemon mode).
Let me know if anything seems wrong! :)
> Add daemons.el support

- evil-collection-notmuch.el
Missing binding to trigger `show-part-map`, which prevents some useful functionality from being exposed to evil-mode (e.g. [integrating diff viewing][1]).
[1]: https://notmuchmail.org/emacstips/#index25h2
> Add binding to trigger notmuch-show-part-map

- evil-collection-notmuch.el
Its exposed in the default mapping but not exposed in the evil mode remapping.
> Expose the tag-all helper to the notmuch-search-mode map

- evil-collection.el
- readme.org
This makes manually configuring things one mode at a time easier since `evil-collection-init` still does all the work.
> Optionally provide modes to evil-collection-init

- evil-collection-git-timemachine.el
Supports evil bindings for git-timemachine. On my machine, git-timemachine
starts with evil in normal mode, which is problematic when trying to access the
keybindings "n" and "p", which navigate to the next and previous revisions.
Additionally, normal mode eclispses "q", which exits the mode.
I tried using `(evil-set-initial-state 'git-timemachine-mode 'motion)`, but that
didn't work. I assume this is because `git-timemachine` is a minor-mode. To work
around this, I used `add-hook` to ensure motion mode was the initial state.
Once motion mode is the initial state, "p" and "q" become available.
Unfortunately, "n" is still unavailable. To get around this, I used a
buffer-local binding in the local motion state to map "n" appropriately. One
known shortcoming of this approach is that there is …
> Support git-timemachine

- evil-collection-emms.el
- evil-collection-evil-search.el
- evil-collection-info.el
I also added "folding" to the emms binds, although, it's not a perfect match (there's no "collapse one tree" command, and "expand-one-level" run repeatedly breaks the tree). For some reason, isearch in emms dosen't seem to search all folds for me, but I don't mind too much, so I'm not touching that for now.
Let me know if anything seems wrong. 
Closes #122
> Use evil-ex-search when requested in info mode

- evil-collection-pdf.el
For PDF files, the default evil search dosen't seem to work at all (for me), so I think it's better to just force isearch on here so people have something.
I also made gg/G scroll to the absolute start/end of the document by scrolling to the top/bottom of the image after navigating to the correct page. This fixes scrolling down a couple lines and then pressing `gg`
> Force isearch in pdf mode

- evil-collection-company.el
This originates from my init file. There are two keymaps in company where one can abort, but by default with "\e\e\e" instead of a single hit. Curiously enough in Evil a single hit works out of the box for regular completion candidates, but in the search it doesn't.  This PR fixes it for the latter.
> Abort company search with single <escape>

- evil-collection-pdf.el
For some reason the count arguments for `pdf-view-next-line-or-next-page` and `pdf-view-previous-line-or-previous-page` only work for `<down>` and `<up>`, but not `j` and `k`. As in, `2 <down>` scrolls down by 2 pages as expected, but `2 j` scrolls down by 2 pages.
After a bit of experimentation, the best solution so far is wrapping the functions in a `dotimes`. After that fix, and both worked for all of the mentioned keys.
> add a count to pdf-tool's next-line-or-next-page

- evil-collection-ediff.el
Btw, maybe it would be good to emit a warning if evil-ediff is also installed, since it can cause a conflict.
cc @justbur
> Fix eval-after-load call in ec-ediff-setup

- evil-collection.el
Sort a copy of the stored bindings, because sort can modify the underlying
object.
> Fix evil-collection-describe-bindings

- evil-collection-helm.el
This makes the minibuffer usable with a few frequently used helm bindings - the unbound evil equivalents either error out or have no effect, so it is best to restore to the default Emacs style binds.
> Fix up helm minibuffer defaults

- evil-collection-neotree.el
This prevents the byte-compiler from trying to expand neotree-make-executor at
compile time when neotree might not be available.
Fixes #158
> Don't byte-compile neotree

- evil-collection-realgud.el
The realgud source buffer is read-only so "u" "d" can be reinstated to execute gdb commands "down" "up"
> realgud: use "d" "u" for realgud:cmd-{newer,older}-frame

- evil-collection-grep.el
- evil-collection.el
This fixes searching in `grep-mode` and derived modes such as `ivy-occur-grep-mode`.
Previously `n` was bound to `next-error-no-select`, so you couldn't easily jump to the next candidate.
> Add evil-collection-grep.el

- evil-collection-deadgrep.el
First of all, thank you for the great collection. Ever since I discovered this, I have been able to remove most of the bindings I had in my config for modes such as IBuffer and Help.
I also noticed that the configuration for Deadgrep mode does not provide bindings to quit the window. This makes it unfortunately annoying to get out of the Deadgrep buffer right now.
I have added them in this PR. I'm not really sure whether the `ZQ` binding is needed here, but I added it for the sake of consistency with the other modes.
Thank you in advance!
> deadgrep: Add bindings (q, ZZ, ZQ) to quit Deadgrep buffer

- evil-collection-log-view.el
Must specify for the specific log-view modes
> log-view: start in normal mode by default

- evil-collection-diff-mode.el
Seems to be standard for bindings for other modes
This is a fix for #193
> diff-mode: allow quitting with 'q'

- evil-collection-package-menu.el
Adds 'gr' bind in normal mode in order to be able to call `package-menu-refresh' when in package-menu-mode.  In default emacs bindings, 'r' is used to refresh, but I thought 'gr' would be more appropriate based on the conventions in the evil-collection README.
> add 'gr' as a bind for `package-menu-refresh' in package-menu-mode

- evil-collection-ediff.el
As the 'evil-collection-ediff-startup-hook' remaps the keybind, add it to
'ediff-keymap-setup-hook' instead of 'ediff-startup-hook'
> Add setup hook to ediff-keymap-setup-hook

- evil-collection-ebib.el
To index mode map, add
- ZZ/ZQ: quitting
- y/p: yank/paste
- C-f/C-b: scrolling
To entry mode map, add
- ZZ/ZQ: quitting
- y/p: yank/paste
- ]/[ and gj/gk: next/prev section
Also inhibit insert bindings in these maps.
> ebib: Reorganize and fill in missing bindings

- readme.org
See the following: https://github.com/emacs-evil/evil-collection/issues/215
I ended up just mentioning it right after it says when those variables must be set. If you rather it be an addition to the Faq, let me know.
> Add mention of other packages loading evil to readme

- evil-collection-mu4e.el
This fixes a fairly major bug where mail could be queued but not shown
to the user.  (This happened to me, I had a month of email sitting in
the queue!)
Since the number of messages in the queue can change, and the status
of queuing mail or direct mail can also change, the display should not
be in a defvar which only gets evaluated once when the library is
first loaded.
This change makes it so the queue status is updated each time the main
mu4e view is drawn.
> mu4e queued mail status needs to be dynamic

- evil-collection-debug.el
Commit https://github.com/emacs-mirror/emacs/commit/e09120d68694272ea5efbe13b16936b4382389d8 introduced this change:
```
(debug-help-follow): Remove.  Move body of this function to
'backtrace-help-follow-symbol' in backtrace.el.
```
> Fix RET in debug-mode-map for emacs 27.

- evil-collection-lsp-ui-imenu.el
This causes lsp-ui to be loaded twice.
To reproduce (in vanilla emacs):
```elisp
(with-eval-after-load 'lsp-ui-imenu ; simulates evil-collection-lsp-ui-imenu
(require 'lsp-ui))
(with-eval-after-load 'lsp-ui
(message "hello"))
(require 'lsp-ui)  ;; -> "hello [2 times]"
```
This complicates configuring lsp-ui with `with-eval-after-load`.
> Load lsp-ui-imenu instead of lsp-ui

- evil-collection-notmuch.el
this is also what would be the case in the emacs state, so it is just a matter of making things consistent
> notmuch: Bind "|" to notmuch-show-pipe-message in notmuch-tree.

- evil-collection-docker.el
- evil-collection.el
Hello,
Don't merge this yet, it's a work in progress.
I'm the author of https://github.com/Silex/docker.el, until now I used this:
``` elisp
(setq evil-emacs-state-modes (append evil-emacs-state-modes '(docker-container-mode docker-image-mode docker-volume-mode docker-network-mode docker-machine-mode))))
```
Then I fell on `evil-collection`, this looks like it could use the same logic for `docker.el`.
* Does it really make sense to add this to `evil-collection`?
* There are 4-5 modes to override (docker-image-mode, docker-volume-mode, etc). Should I override them all in one file or in several files?
> Support docker.el

- evil-collection-docker.el
- evil-collection-tablist.el
- evil-collection.el
Hello,
Before you merge this I need guidance: this does not work.
Here is how `docker-image-mode` works:
``` elisp
(define-derived-mode docker-image-mode tabulated-list-mode "Images Menu"
"Major mode for handling a list of docker images."
(setq tabulated-list-format [("Repository" 30 t)("Tag" 20 t)("Id" 16 t)("Created" 23 t)("Size" 10 docker-image-human-size-predicate)])
(setq tabulated-list-padding 2)
(setq tabulated-list-sort-key docker-image-default-sort-key)
(add-hook 'tabulated-list-revert-hook 'docker-image-refresh nil t)
(tabulated-list-init-header)
(tablist-minor-mode))
```
It's a major mode that enables the minor mode `tablist-minor-mode`.
Any idea what I am missing for it to work? Should I call `evil-collection-tablist-setup` from within `evil-collection-docker-setup` ? …
> Add tablist

- evil-collection-grep.el
By default this is bound to describe-mode, which is easily accessible
through other means.
> Fix "h" in grep mode

- evil-collection-notmuch.el
Simple one line fix that prevented notmuch-search-toggle-flagged to work
> Fix notmuch-search-toggle-flagged

- readme.org
Making the list more complete.
Also pinging @Somelauw on the chance that they want to integrate their package into `evil-collection`.
> Add evil-markdown to third-party packages in readme

- modes/dired/evil-collection-dired.el
`dired-subtree` allows the insertion of a subtree in place instead of at the bottom of the buffer, as `dired-maybe-insert-subdir` would. Unfortunately `dired-subtree` does not come with a minor mode to cleanly separate keybindings, so I inserted a `featurep` check if `dired-subtree` is available, as it makes sense to overwrite one or more bindings from `evil-dired`.
`dired-subtree` is interesting by itself as it makes navigating directories a bit easier, but it is also a requirement for `dired-sidebar`, a candidate for addition to `evil-collection`.
P.S.: This is my first proper pull request, please advise if I'm doing something wrong.
> Add bindings for dired-subtree

- modes/tablist/evil-collection-tablist.el
This restores it to 'evil-previous-line.
Fixes #272.
> Free up `k` in tablist

- modes/unimpaired/evil-collection-unimpaired.el
Adds `] SPC` and `[ SPC` keybindings to `evil-collection-unimpaired` to insert an empty line above or below the current line.
See [vim-unimpared docs](https://github.com/tpope/vim-unimpaired/blob/ab7082c0e89df594a5ba111e18af17b3377d216d/doc/unimpaired.txt#L64)
> Add insert empty line above/below functionality to unimpaired

- modes/tablist/evil-collection-tablist.el
This move `tablist-do-kill-lines` to `K` like in `dired` and `ibuffer`.
> Improve tablist bindings

- modes/dired/evil-collection-dired.el
I originally created `evil-collection-dired-filter` directory, then realised it belongs to dired.
It relies on `dired-filter-mark-map` being assigned last so it overwrites the default bindings like `**` etc.
> Add dired-filter

- modes/gnus/evil-collection-gnus.el
There were two different `C-k` keybindings, so I removed the one for `gnus-summary-kill-same-subject`. Now `C-j` and `C-k` behave in a similar way.
The `k` keybinding was conflicting with `evil-previous-line`, so I removed that one too.
> Fix conflicting keybindings in gnus configuration

- modes/vterm/evil-collection-vterm.el
emacs-libvterm@376db7cf416 had a breaking change for
`vterm-exit-functions` which sends the event as the second argument.
> vterm-exit-functions now sends event as 2nd arg.

- modes/pdf/evil-collection-pdf.el
I noticed that there where no keybindings defined to toggle the visibility of children in `pdf-outline-mode`. This PR adds this functionality.
> Add keybindings for toggling children in pdf-outline-mode

- modes/outline/evil-collection-outline.el
`zb` is usually bound to `evil-scroll-line-to-bottom`. By moving `outline-hide-entry` to `zE`, you also get more consistency because `ze` is bound to `outline-show-entry`.
It fixes https://github.com/emacs-evil/evil-collection/issues/292
> Do not override `zb` in outline mode.

- modes/dired/evil-collection-dired.el
- modes/help/evil-collection-help.el
- modes/info/evil-collection-info.el
- readme.org
I added a guideline to readme.org. For now, I just ensured terminal compatibility for dired, help, and info modes.
This fixes https://github.com/emacs-evil/evil-collection/issues/290
> Start ensuring terminal compatibility.

- modes/magit-todos/evil-collection-magit-todos.el
"jT" in `magit-todos-item-section-map` prevents evil users from stepping into the section too, this PR fix it
> Magit-todos: unbind "j" in magit-todos-item-section-map

- modes/ebuku/evil-collection-ebuku.el
Further to [this user request](https://github.com/flexibeast/ebuku/issues/8), i'd like to add support for Ebuku to evil-collection.
i only use evil-local-mode, myself, and only occasionally at that, so i'm not sure of the extent to which the Evil keybindings should differ from the non-Evil ones, given the evil-collection guidelines. Any recommendations in this regard would be much appreciated. :-)
> Add `evil-collection-ebuku`.

- modes/helpful/evil-collection-helpful.el
There wasn't a binding for `helpful-visit-reference`, so I added it.
> Helpful: add binding for visiting reference

- evil-collection.el
- modes/dashboard/evil-collection-dashboard.el
Added bindings to [Dashboard](https://github.com/emacs-dashboard/emacs-dashboard)'s own commands, like next/previous section, refreshing the buffer, and jumping to sections.
I had to use an advice as dashboard.el defines some commands (the ones that jump to sections) as unnamed functions bound to a local variable, *after* the other parts of the map has been defined.
> Add bindings for Dashboard

- modes/dashboard/evil-collection-dashboard.el
- modes/ebuku/evil-collection-ebuku.el
Recently introduced evil-collection-ebuku.el and evil-collection-dashboard.el require third-party packages directly, which causes byte-compile error when install from MELPA.
----
#
> fix byte-compile errors

- modes/gnus/evil-collection-gnus.el
Added bindings for the remaining 3 gnus modes (group, server, and
browse) and also reworked some bindings that seemed unintuitive.
These aren't perfect, but it's a start. When I started using gnus it was jarring for only some of the modes to be supported. This fixes that problem.
It compiles using cask, and the linter didn't throw any new warnings
> Updated gnus bindings

- modes/unimpaired/evil-collection-unimpaired.el
Related to #320.
Also, took `save-excursion` out of the loop, to make it executed only once instead of calling it on each iteration.
> Fix bug in unimpaired module.

- evil-collection.el
- modes/imenu/evil-collection-imenu.el
Adding imenu navigation to the jump list is natural, since many or most other navigation actions already add to the jump list by default. (Search for `:jump` in [evil-commands.el](https://github.com/emacs-evil/evil/blob/master/evil-commands.el.) to see.)
> Add imenu jumps to the Evil jump list

- modes/mu4e/evil-collection-mu4e.el
Changed mu4e d key-bind in mu4e-headers-mode-map form
mu4e-headers-mark-for-trash to mu4e-headers-mark-or-move-to-trash.
Changed mu4e d key-bind in mu4e-view-mode-map form mu4e-view-mark-for-trash to mu4e-view-mark-or-move-to-trash.
> Changed mu4e d key-bind

- modes/pdf/evil-collection-pdf.el
Currently `evil-collection-pdf-view-goto-{first,last}-page` are calling `image-bob` and `image-eob`, which not only scroll to the bottom of the image (pdf page), but they also change the horizontal scrolling to either the left edge of the image or the right edge of the image. This is somewhat unexpected behavior (to me).
My reasoning is:
If you have a book / document that has large margins, you might want to zoom in to maximize your view of the text. Today with pdf-view scrolling through the PDF / flipping pages your centering is preserved. I think the behavior should be similar for going to the first & last pages. Today, if you go the first page you are sent to the top of the first page and you are scrolled all the way to the left side of the page.
> Change pdf-view first & last page to preserve hscroll

- modes/pdf/evil-collection-pdf.el
C-u and C-d will trigger respectively:
- pdf-view-scroll-down-or-previous-page
- pdf-view-scroll-up-or-next-page
In order to reflect evil/vim C-u and C-d
> Add C-u and C-d to pdf-view-mode-map

- modes/debug/evil-collection-debug.el
There's no `debugger-toggle-locals`, only `backtrace-toggle-locals` exist.
> ec-debug: replace debugger-toggle-locals with backtrace-toggle-locals

- modes/vterm/evil-collection-vterm.el
This PR fixes the delete key for vterm, and adds bindings to jump to the previous or next prompt.
> Add delete and prev/next prompt bindings for vterm

- modes/info/evil-collection-info.el
> Info-exit is marked obsolete since 27.1, use quit-window instead

- modes/package-menu/evil-collection-package-menu.el
Hi,
I heavily use the function package-menu-describe-package in the package buffer to show a long description of a package, and also to get the hyperlink to access the source code. This function, bound to "?" in emacs mode, is very nice as it can be called anywhere on a package line.
I would like to rebind it to "g?", as it seems to be the practice in other modes to show something related to "show help". And it keeps the "?" shortcut to search backward for text (which is also useful in this mode).
I'm open to any discussion on the validity of this mapping.
Regards,
Nicolas
> package-menu: add keybinding for package-menu-describe-package

- modes/eshell/evil-collection-eshell.el
I noticed that doom emacs supports `cc` and `dd` commands for changing or deleting everything except the prompt, so I decided to copy the relevant code to evil-collection.
> add cc and dd command to eshell (copying Doom's implementation)

- modes/help/evil-collection-help.el
- modes/info/evil-collection-info.el
- readme.org
> Add `g TAB` as a substitute on terminal for Tab.

- modes/doc-view/evil-collection-doc-view.el
Currently getting bound to image-scroll-up and image-scroll-down from evil-collection-image.el. Not sure if it is relevant, but evil-collection-image.el has a TODO referencing this closed issue: https://github.com/emacs-evil/evil-collection/issues/23
> SPC, DEL, S-SPC scroll binds for DocView

- evil-collection.el
- modes/tabulated-list/evil-collection-tabulated-list.el
I noticed when using the buffer-menu (M-x buffer-menu) I couldn't use n for evil-search-next or gg for evil-goto-first-line. This patch fixes that.
> fix bindings for `buffer-menu'

- modes/company/evil-collection-company.el
This allows `company-mode` popup only showing up while we're in insertable state.
Related issue https://github.com/emacs-lsp/lsp-mode/issues/1447
> ec-company: showing popup only when in insertable state

- evil-collection.el
- modes/rg/evil-collection-rg.el
`i` is bound to `rg-rerun-toggle-ignore` meanwhile `I` is bound to `wgrep-change-to-wgrep-mode`.
Should I swap the bindings?
> rg: add evil bindings

- evil-collection.el
- modes/org-present/evil-collection-org-present.el
This is a pull request for #370 
Feel free to edit as you see fit and please do let me know if you have any questions.
I still haven't been able to successfully load the keybindings in my emacs.
I am getting the following error:
```Symbol's value as variable is void: org-emph-re```
I have a feeling this might be an issue with my environment variables and emacs but I'm not sure at the moment.
I have my emacs packages installed with guix except for evil-collection which I installed by cloning this repo and sourcing it in my ```~/.emacs```.
\- Carla
> Add org-present

- modes/tabulated-list/evil-collection-tabulated-list.el
The original bindings make no sense.
``` elisp
(evil-collection-define-key nil 'tabulated-list-mode-map
"n" nil
"p" nil)
```
> tabulated-list: add more bindings

- modes/gnus/evil-collection-gnus.el
In addition,
- Rebind gnus-summary-mail-forward from C-c C-f to cf
- Remove E gnus-article-read-summary-keys which is not much useful
> gnus: R can reply in normal state.

- modes/eglot/evil-collection-eglot.el
eglot-help-at-point has been removed since: https://github.com/joaotavora/eglot/commit/a044dec7f94d0d21bd65cf8a04f09cc63324db18
> eglot: update binding

- modes/hungry-delete/evil-collection-hungry-delete.el
Remove `(interactive)` specs of `evil-collection-hungry-delete` and `evil-collection-hungry-delete-for-join` as they break `evil-collection-hungry-delete` and `evil-collection-hungry-delete-for-join` when `hungry-delete-mode` is bound but not enabled.
This fixes issue #386.
> Fix #386: Remove broken (interactive) specs

- modes/gnus/evil-collection-gnus.el
The `j`/`k` bindings are removed to make `gnus-group-yank-group` work when all topics are empty.
> gnus: add topic commands

- evil-collection.el
- modes/indent/evil-collection-indent.el
`indent.el` has no `(provides 'indent)` since it's autoloaded.
> indent: add evil style bindings for `indent-rigidly'

- modes/compile/evil-collection-compile.el
- modes/simple/evil-collection-simple.el
Before this change compilation bindings didn't work in grep-mode which inherits
compilation-minor-mode-map
> compile: Apply bindings to compilation-minor-mode-map

- evil-collection.el
- modes/org-present/evil-collection-org-present.el
- modes/shortdoc/evil-collection-shortdoc.el
`shortdoc` comes from Emacs 28 which has not been released yet so I temporaily
set `Package-Requires` to ``((emacs "27.1"))`` otherwise `package-lint` will
fail.
Additionally the trailing whitespaces in org-present mode are removed.
> Add shortdoc evil bindings

- evil-collection.el
- modes/racket-describe/evil-collection-racket-describe.el
A help mode to look up Racket documentation inside Emacs.
> Add racket-describe

- Cask
- Makefile
- modes/magit/README.org
- modes/magit/evil-collection-magit.el
- test/evil-collection-magit-tests.el
@justbur @Ambrevar @noctuid 
Quickly pulled over the evil-magit files, changed the namespace, and made a few tweaks around initialization.
Starting it up without the original evil-magit seems to work. README and makefile/testing could probably use some attention since I didn't try to run the test. It'd be nice if we could just get one "test" command to run through all our tests (well we only have evil-magit right now).
> Port over evil-magit

- modes/prodigy/evil-collection-prodigy.el
Hey there, I added some keybindings that were missing on prodigy-view-mode compared to prodigy-mode. This mode is different from prodigy-mode but has similar actions.
> prodigy: add more keybindings to prodigy-view-mode from prodigy-mode

- modes/occur/evil-collection-occur.el
This fixes the C-j and C-k behavior discussed in #408 .
I went with the `-no-select` versions of `next-error` and `previous-error` since these retain focus in the occur buffer while navigating the results with preview (as opposed to visiting the locations and moving focus to the original window).
> Occur mode C-j and C-k

- Cask
- evil-collection.el
- modes/dictionary/evil-collection-dictionary.el
This is for Emacs's standard [dictionary-mode](https://www.emacswiki.org/emacs/DictMode). The actual major mode is named `dictionary-mode` notwithstanding the title of that wiki page.
Dictionary mode binds `h` to `dictionary-help` which shows the default keybindings for the mode - most of which are still active even under the evil bindings so this is still relevant. Since `h` should be bound to `backward-char` under evil, I bound that function to `?`. Is there a convention or precedent to follow here, or is this fine as is?
> Add basic support for dictionary-mode

- modes/dictionary/evil-collection-dictionary.el
#411 adds evil bindings to dictionary-mode without `(require 'dictionary nil t)` which will lead an error:
``` text
Cannot open load file: No such file or directory, dictionary
```
> Suppress dictionary nonexistence error

- modes/edebug/evil-collection-edebug.el
j, k, l are used for navigation in edebug-mode and so should do h.
However, currently it performs "edebug-goto-here", which is also bound
to H. Therefore, "h" is free to be used for navigation.
> edebug: "h" should behave the same as j, k, l

- modes/newsticker/evil-collection-newsticker.el
``` emacs-lisp
k newsticker-previous-item
j newsticker-next-item
```
The bindings are removed
> newsticker: add treeview bindings

- Cask
- evil-collection.el
- modes/ripgrep/evil-collection-ripgrep.el
[rg](https://github.com/dajva/rg.el) and [deadgrep](https://github.com/Wilfred/deadgrep) are already supported. This adds support for [ripgrep](https://github.com/nlamirault/ripgrep.el), yet another ripgrep frontend, and the one that happens to be [used by projectile](https://github.com/bbatsov/projectile/blob/0ff73ecf7f25f47382e2d28c8ab232c18609d515/projectile.el#L3428-L3437).
I followed the `grep` recipe to add minimal support for navigating the search results.
I also removed `dictionary` from the Cask dependencies since it looks like with [this change](https://github.com/emacs-evil/evil-collection/pull/413), it isn't needed anymore.
> Add basic support for ripgrep

- modes/notmuch/evil-collection-notmuch.el
Since all the other maps in `evil-collection-notmuch-maps` 
have notmuch-common-keymap as parent
https://git.notmuchmail.org/git?p=notmuch;a=blob;f=emacs/notmuch-hello.el;h=fa31694ff0f79a7f2781849394390a673f75aade;hb=HEAD#l651
When `evil-collection-setup-hook` runs, if it changes keymaps
using a `dolist` over `evil-collection-notmuch-maps`, then a binding might
see 2 changes at once.
See discussion here https://github.com/hlissner/doom-emacs/pull/4403#issuecomment-750907188
> Put notmuch-common-keymap last

- modes/magit/evil-collection-magit.el
Both should do the same thing, which is magit-section-{forward,backward}-sibling.
----
#
> magit: make gj/gk behave consistently

- modes/outline/evil-collection-outline.el
Hi,
This PR adds a setting that exposes the Outline mode bindings in Outline minor mode. It's turned on by default. As noted in the docstring, a user can override or exclude specific bindings with `evil-define-minor-mode-key`.
Thanks!
*EDIT*: simplified/corrected the new setting's docstring
> outline: Optionally enable keybindings in Outline minor mode

- modes/ebib/evil-collection-ebib.el
The original ebib involing a function to hide ebib without quit it which can
make some features like completion to work.
> Replace ZZ to ebib lower

- modes/elisp-mode/evil-collection-elisp-mode.el
`evil-collection-elisp-mode-ielm-repl` will open a new window while `ielm` use current window. Since it's a REPL, the former is more intuitional
> elisp-mode: Binds gz to ielm

- modes/elfeed/evil-collection-elfeed.el
elfeed binds `q` to `elfeed-search-quit-window` which saves the db and
quit the window. As today we only close the window which may lead to
data loss.
> elfeed: Bind q, ZQ, ZZ to elfeed-search-quit-window

- modes/company/evil-collection-company.el
The `evil-collection` package inhibits `company-mode` from showing completions when evil-mode
is switched off. This commit will fix it and only activate `evil-collection` advice for `company-mode`
when in `evil-mode`.
If applied, this commit will:
* Allow `company-mode` to show completions when not in `evil-mode`.
* Only activate `evil-collection` advice for `company-mode` when in `evil-mode`.
* Fixes #451 .
> fix: Stop inhibiting company popup when not in evil-mode

- evil-collection.el
- modes/elfeed/evil-collection-elfeed.el
- modes/eww/evil-collection-eww.el
- modes/info/evil-collection-info.el
- modes/mu4e/evil-collection-mu4e.el
- modes/notmuch/evil-collection-notmuch.el
- modes/pass/evil-collection-pass.el
- modes/transmission/evil-collection-transmission.el
- modes/vdiff/evil-collection-vdiff.el
- modes/w3m/evil-collection-w3m.el
Some context: https://github.com/emacs-evil/evil-collection/pull/91#issuecomment-366181047
https://github.com/emacs-evil/evil-collection/commit/6bdbcccf1e4f51c75f5cf54b3dc27419b32fe608
This is for attaching additional keys to operator commands.
e.g. Add "f" to prefix/operator (evil-yank) "y" to get
"yf"
while still maintaining the other operator commands like "yy".
Would be happy if you had time to take a look @noctuid, curious if general has something already for this use case.
@condy0919 Appreciate a look before I merge.
> Add evil-collection-define-operator-key

- modes/unimpaired/evil-collection-unimpaired.el
Currently when you use `]l` or `[l`, moving to next/previous error gets set as the vim repeat, so hitting `.` after `]l` will repeat jumping to the next error. As this is just a motion and not an actual edit, it breaks expectations as to what `.` should do, and prevents you from jumping from error to error, visually assessing them quickly, and using `.` to fix them if they are broken in the same way by doing things like `]l.]l.]l.]l.]l.`.
Using `evil-without-repeat` seems to fix it for me when testing locally, but I'm not sure if there's a more proper way of doing this in an `evil-collection` context.
Thanks for the great work!
> fix: don't set repeat with ]l and [l error jump

- modes/magit/evil-collection-magit.el
"O" is used to launch `magit-reset`, not `magit-revert`. "\_" and "-" should be used for the suffix commands to be consistent with the prefix key "\_".
> Magit: Keep bindings consistent with prefix key in magit-revert

- modes/ivy/evil-collection-ivy.el
This PR fixes issue #474 (also raised by me).
This fixes the problem: If a user switches to Emacs mode/evil-emacs-state (quite useful for editing magit commit messages, or working in vterm/term), the `<escape>` key cannot work its classic Meta-functionalities, such as interpreting `<escape> f` as `M-f`, or `<escape> b` as `M-b`.
For further details, please kindly refer to issue #474.
> Fix escape in in emacs-state, yet preserving minibuffer quit functionality

- modes/magit/evil-collection-magit.el
This change adjusts the formatting of the instructions in the `git-rebase`
buffer to allow them to be properly formatted when git's `core.commentChar` is
set to `%`.  In particular, lines will look something like this:
```
%-8s p
```
The root cause seems to be the how the lines are constructed: comment characters
are directly added to the format string.  When it is `%`, `format` appears to
proceed until it finds the next `%` character, (corresponding to the `%` in
`%-8s`) above and prints it directly to the string rather than interpreting it
something to format.
This is fixed by constructing the format string with the comment character as an
argument to `format` rather than being added directly to the format string.
Fixes #468.
> Magit: Properly format rebase instructions when commentChar is "%"

- modes/prodigy/evil-collection-prodigy.el
`prodigy-jump-dired` does not exist. `prodigy-jump-file-manager` is
likely the intended function.
> Fix Jd binding

- modes/reftex/evil-collection-reftex.el
I noticed that the help message for refTeX-TOC did not specify the evil bindings and I suppose that it was because the refTeX-TOC prompt could not be changed from this add-on since it was hard-coded in the original file [here](https://github.com/emacs-mirror/emacs/blob/3e41eccc27586fd9e24369a2c82db483a97ad9eb/lisp/textmodes/reftex-toc.el#L267).
However, all but one of the keybindings in the prompt are the same in the evil-bindings so I do not see a point in not showing the help message with evil-bindings.
> Added help prompt for reftex-toc (with comments)

- modes/magit/evil-collection-magit.el
`magit-show-refs-popup` and `magit-dispatch-popup`
have been renamed without "-popup".
Define magit-show-refs as a transient command
https://github.com/magit/magit/commit/c3135cdb23e223ebf8f3c802616ebb81103fdbe9
Define magit-dispatch as a transient command
https://github.com/magit/magit/commit/dde9a5b77a483fa35d932aecd22c1a4c954ce77e
And make the docstring more readable,
with the related key and command on the same line.
This variable name contains: `magit-dispatch-popup`
https://github.com/emacs-evil/evil-collection/blob/09b165d4c2ecac66224f674966c920c25d20f3f6/modes/magit/evil-collection-magit.el#L557
and it's used here:
https://github.com/emacs-evil/evil-collection/blob/09b165d4c2ecac66224f674966c920c25d20f3f6/modes/magit/evil-collection-magit.el#L613
I don't know if it also should be …
> Docstring: evil-collection-magit-use-y-for-yank

- modes/tide/evil-collection-tide.el
Current implementation seems to only work for the first reference in a file. This patch should fix that.
> Tide/references mode: Go to reference at cursor

- modes/transmission/evil-collection-transmission.el
`transmission-delete` and `transmission-remove` have different purposes and
should both be included as bindings.
`transmission-delete`: Removes torrent from Transmission client and unlinks files from drive.
`transmission-remove`: Removes torrent from Transmission client.
`I` has been set to inputting labels for torrents using `transmission-label`.
> [transmission] Fix keybinding

- evil-collection.el
- test/evil-collection-test.el
Solves #465 by defining `evil-collection-state-passlist` and `evil-collection-state-denylist` analogous to `evil-collection-key-{black,white}list`.
If you find the new variable names alien to the latter's, please tell me to rename them. I also prefer the old naming scheme but have seen the trend such as `native-comp-deferred-compilation-deny-list`.
> Make filtering states possible

- modes/magit/evil-collection-magit.el
Without using `kbd', each key in the string "\<escape>" is interpreted as a
prefix key.
> Properly bind escape in magit-mode-map

- modes/elfeed/evil-collection-elfeed.el
The command that resets the search filter to it's default value, `elfeed-search-clear-filter`, was missing it's keybinding.
elfeed bind this to `c` by default.
> [elfeed]: add missing keybind

- modes/consult/evil-collection-consult.el
internal function needed to be updated inline with an upstream
change. The `markers` variable is ignored and only current-buffer evil
marks are shown.
> update evil-collection-consult--mark-candidates for upstream change

- modes/telega/evil-collection-telega.el
1. yy and yl is conflicted with the evil yank commands.
2. Reply is more common than forword and r is reply in default of telega.
Advice from @cnsunyour @yangsheng6810 and do you have more suggestions for improvement?
> Modify telega keybinding for copy and reply

- modes/grep/evil-collection-grep.el
Support is mentioned in the README but isn't implemented for the vanilla `grep-mode`.
> Wgrep support for grep for other package managers

- modes/debug/evil-collection-debug.el
Debugger mode bindings for backtrace-multi-line and backtrace-single-line.
> debug: added bindings for toggling multi-line

- .github/workflows/build.yaml
This changes the deprecated cask install method to the new suggested method.
> Change depricated cask installation method

- modes/mu4e/evil-collection-mu4e.el
As part of the move to the gnus viewer for emails, the command name has been
changed from `mu4e-view-attachment-action` to `mu4e-view-mime-part-actions`.
https://github.com/djcb/mu/issues/2101#issuecomment-903074743
> mu4e: update binding for attachment actions

- evil-collection.el
- modes/beginend/evil-collection-beginend.el
Hey,
[beginend](https://github.com/DamienCassou/beginend) is a mode that changes the behaviour of `M-<` and `M->` under normal Emacs bindings to go to the beginning of the buffer that makes sense. For example, the top of the first section in `magit-status` instead of the first line.
With this PR, we bring that behaviour to `gg` and `G` bindings under Normal state in Evil Mode.
Thanks.
> beginend: add basic support

- evil-collection.el
- modes/selectrum/evil-collection-selectrum.el
Hey,
First of all, thanks for the truly wonderful package. My jump to Evil Mode (again!) wouldn't be complete without it.
In this PR, I have added basic support for [Selectrum](https://github.com/raxod502/selectrum), which I found to be lacking here.
I have tried my best to mimic either Helm or Ivy keybindings with this PR. I don't see `C-j` and `C-k` being bound for navigating between candidates in Ivy or Helm. However, I have found it to be useful. I can remove this if it goes against normal Evil Collection semantics.
Open to any other suggestions or changes. Thanks again.
> selectrum: add initial support

- modes/comint/evil-collection-comint.el
In Vim insert mode, C-u deletes to the beginning of the line, so we
make an analogous binding for comint buffers.
> comint: Bind comint-kill-input to C-u

- evil-collection.el
- modes/yaml-mode/evil-collection-yaml-mode.el
Very basic support for yaml-mode in order to support correct indentation width with evil-shift
> yaml: basic support

- modes/beginend/evil-collection-beginend.el
As discussed in #533, this PR provides a fix to ensure number-prefixed `gg` and `G` motions do not break when `beginend` support is enabled.
> beginend: ensure num-prefixed motions do not break when enabled

- modes/beginend/evil-collection-beginend.el
I noticed that on the master branch, the dired-mode stuff wasn't working since it hadn't been manually typed into the setup function. So I think we should simply iterate over the defconst instead.
cc @balajisivaraman
> beginend: evil-collection-beginend-maps -> [...]-modes, and iterate

- modes/consult/evil-collection-consult.el
This PR implements a consult command which allows you to browse the evil jump list with consult preview and completion.
In a separate commit, I've also simplified the implementation of evil-collection-consult-mark a bit by removing unnecessary usage of advice. This can be dropped or moved to a separate PR depending on maintainers' preference.
Thanks in advance.
> consult: implement jump-list command

- modes/smerge/evil-collection-smerge-mode.el
Added Smerge bindings according to #519, does follow spacemacs bindings as declared here(https://github.com/syl20bnr/spacemacs/pull/8505)
Keybindings start with 'g' prefix.Changes are welcome!
> Added Smerge Mode Bindings

- modes/forge/evil-collection-forge.el
evil-collection handles this, and the default bindings produce an error message
on startup.
> Prevent forge from binding default keys

- modes/company/evil-collection-company.el
Adds Cntrl-X bindings according to #308 for company completion in evil-mode.
Currently added
- C-o: company-capf
- C-]: company-etags
- C-s: company-ispell
- C-f: company-files.
Notable missing keybindings
- company-dict-or-keywords (C-k is taken).
The `+company/whole-lines`  and other `+company` functions is taken directly from `doom-emacs`. It works without problem in my own emacs configuration.
Changes are welcome!
> Ctrl x bindings

- modes/notmuch/evil-collection-notmuch.el
Default notmuch keymaps bind A to
notmuch-tree-archive-thread-then-next in both notmuch-show-mode and
notmuch-tree-mode.
> notmuch: use notmuch-tree-archive-thread-then-next in tree view

- modes/magit/evil-collection-magit.el
This little mistake broke the native magit `C` binding because the keybinding was now `C - u` rather than `C-u` ^^
> Fix C-u scroll in magit config

- modes/compile/evil-collection-compile.el
Same idea that is used in, e.g., `evil-collection-help.el`.  In particular, it binds `q` to `quit-window`.
> Set readonly bindings for compilation mode

- modes/magit/evil-collection-magit.el
- modes/tetris/evil-collection-tetris.el
Escape usually means to:
1. Return to normal mode.
2. Abort the minibuffer.
By binding it to quit-window (or equivalent), hitting escape a few times to exit a (potentially recursive) minibuffer, etc. can cause buffers to vanish.
It's also:
1. Inconsistently applied. These are the only two modes that have escape bound this way.
2. Redundant with "q" (which is consistently applied).
> Avoid binding escape to bury-buffer and quit-window

- modes/doc-view/evil-collection-doc-view.el
- modes/image/evil-collection-image.el
I found that these keys were bound to the normal character/line Evil motions in normal state. This changes them to have the same bindings that they have in the Emacs state.
> Bind arrow keys in Doc View mode.

- modes/forge/evil-collection-forge.el
With Magit and Forge defaults bindings, the "n" key allows you to create a new branch (without checkout/branch change) in "magit-branch" transient window. Evil-collection-forge overrides this binding (the "n" key is used to checkout a pull-request) . So there is no more binding to create a new branch (without checkout) as we can see in this screenshot (third column):
This PR restores defaults bindings in "magit-branch" transient window:
> magit/forge: restore defaults bindings in magit-branch transient

- modes/mu4e/evil-collection-mu4e.el
The newest version of mu4e adopts new names for main-action-str and main-view-queue.
> update new function names of mu4e's main-action-str and main-view-queue

- modes/mu4e/evil-collection-mu4e.el
This accommodates everyone using a version of mu4e shipped with their
package manager's installation of mu.
> mu4e: use newly-renamed functions as aliases when appropriate

- modes/ibuffer/evil-collection-ibuffer.el
Hello,
1. I find it frustrating that `t` behaves differently between `dired` and `ibuffer`.
2. Ibuffer `* *` is the same as `U`, it's more interesting for it to mean `mark special buffers` (the temporary ones, which start or end with `*`). That way when we want to get rid of all these `*` buffer the mnemonic is easy: press `* * D RET`
> Make ibuffer bindings consistent with dired

- readme.org
This adds a hint in the readme on passing a list to `evil-collection-init`.
> Add hint on passing a list to evil-collection-init

- modes/selectrum/evil-collection-selectrum.el
This adds bindings for the following commands:
| Command                    | Binding | 
|----------------------------|---------|
| `selectrum-next-group`     | `gj`    |
| `selectrum-next-group`     | `gj`    |
| `selectrum-previous-group` | `gk`    |
| `selectrum-goto-end`       | `gg`    |
| `selectrum-goto-beginning` | `G`     |
| `selectrum-kill-ring-save` | `gy`    |
> Bind other Selectrum commands.

- modes/ebib/evil-collection-ebib.el
Change mapping for "y" in ebib-entry-mode to "ebib-copy-current-field-contents" instead of "ebib-copy-field-contents" since the latter is not a command.
> ebib: change mapping for "y" in ebib-entry-mode.

- evil-collection.el
- modes/eshell/evil-collection-eshell.el
@noctuid Would love your thoughts on this. Think introducing this abstraction for these wonky modes with really late keymap initializations is good considering the hook's original purpose was to allow setting these types of binds after the bind exists is and already mapped.
This shouldn't affect how user's use the hooks as it'll get called at some point..
@condy0919
> Delay running `evil-collection-setup-hook` for modes like eshell (#602)

- modes/help/evil-collection-help.el
This pull request adds keybindings for the new help-mode commands introduced in Emacs 28. See also: https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS.28#n558
> Add bindings for the new help-mode commands

- modes/info/evil-collection-info.el
I have noticed that there is no equivalent to `Info-index-next` in evil-collection-Info. In vanilla emacs, it is bound to `,`. I believe that `g,` is the most logical evil-equivalent.
> Add "g," as a keybinding for `Info-index-next'

- modes/vterm/evil-collection-vterm.el
I baesd the implementation on `evil-substitute` and
`evil-change-whole-line`.
> vterm: add vterm-substitute and vterm-substitute-line

- modes/vterm/evil-collection-vterm.el
We have `0` for jumping at the very first character of the current
line and `^` for jumping to the non-blank character. It is useful to
keep this distinction in `vterm` buffers. However, it doesn't make
much sense in the command part. Because we have a prompt, both of the
commands jump to the very first character. I think it would be more
useful to change `^` to jump to the first non-blank character after
the prompt.
> vterm: use ^ for jumping at the beginning of the command but after prompt

- modes/vterm/evil-collection-vterm.el
The `vterm-yank` that is currently bound to `p` actually pastes before
the cursor, so I am rebinding it to `P` and adding a function for
pasting after the cursor.
> vterm: fix paste-before and add paste-after command

- modes/compile/evil-collection-compile.el
Currently, it's bound to evil-jump-forward, which isn't useful in compile-mode.
> compile: bind TAB to compilation-next-error

- evil-collection.el
NA
NA
Currently `ebuku`'s keybinding is already in [modes](https://github.com/emacs-evil/evil-collection/tree/master/modes/ebuku), however, it's not in the `el` file, so users needs to manually trigger it either appending it to `evil-collection-mode-list` before init or directly do `(evil-collection-init 'ebuku)`.
> add ebuku to supported modes

- modes/realgud/evil-collection-realgud.el
As the title sais.
Before both `H` and `U` both where bound to the command `realgud:cmd-until` and there was no key for 
the function `realgud:cmd-until-here`
> Bind `H` to `realgud:cmd-until-here`

- modes/dired/evil-collection-dired.el
The following 3 commands are not defined in `dired.el` and are not available until `dired-x.el` is loaded:
- `dired-mark-sexp`
- `dired-mark-extension`
- `dired-mark-omitted`
> dired: separate definition of dired-x bindings

- modes/mpdel/evil-collection-mpdel.el
> [mpdel] Modify song seek keybindings from three to two keys

- modes/xref/evil-collection-xref.el
This matches how the keys behave in other modes. Otherwise they are bound to `evil-paste-pop` which isn't valid in xref buffers.
> Use `C-n` and `C-p` for navigation in xref

- modes/vterm/evil-collection-vterm.el
vterm: currently, typing `a` in normal mode moves the cursor 2 characters to the right. 
We either (+ 1 (point)) and call evil-insert or evil-append at (point).
> Correct cursor position when evil-append in vterm

- modes/vterm/evil-collection-vterm.el
The behaviour of evil and evil in vterm should be consistent
> vterm: use x to delete char and X to delete backward char

- modes/vterm/evil-collection-vterm.el
The original `evil-first-non-blank` isn't usable because the beginning
of the prompt is the first non-blank character. Strangely enough,
`vterm-beginning-of-line` didn't work either.
> vterm: when deleting command with `dd`, reset cursor after prompt

- evil-collection.el
- modes/snake/evil-collection-snake.el
Adds support for `snake` game
https://github.com/wickedjargon/evil-collection
> snake: initial support

- evil-collection.el
- modes/bluetooth/evil-collection-bluetooth.el
Added support for [bluetooth](https://gitlab.com/rstocker/emacs-bluetooth) by redefining the keys ignored by `tabulated-list`
https://github.com/arian-d/evil-collection
> Added blutooth-mode bindings

- evil-collection.el
This is causing CI to fail on Emacs snapshot.
> Placate docstring complaint

- modes/org-present/evil-collection-org-present.el
I think it's better to have j, k and w keys to remain their function inside org-present view, so people can navigate their cursor more easily.
> Changed some keys, so user can navigate the cursor during present.

- modes/mu4e/evil-collection-mu4e.el
`mu4e-view-save-attachment-multi` does not exist anymore. I'm not sure whether we should delete this keybinding directly.
> mu4e: replace obsolete mu4e-view-save-attachment-multi

- modes/mu4e/evil-collection-mu4e.el
delete the redundant keybinding as discussed in https://github.com/emacs-evil/evil-collection/pull/660#issuecomment-1188723037
> mu4e: delete the redundant keybinding

- modes/unimpaired/evil-collection-unimpaired.el
> unimpaired: repeat-mode integration

- modes/mu4e/evil-collection-mu4e.el
Should fix #528. I haven't written elisp/contributed to software like this before; sorry in advance for any silly errors. 
Note: checkdoc is happy with new changes. I didn't fix old checkdoc errors.
> Update mu4e-main Maildirs section

- modes/pdf/evil-collection-pdf.el
`pdf-tools` has functions for navigating in jump history. This PR simply adds 
standard bindings to these functions. The prefix counters are also supported.
https://github.com/vedang/pdf-tools
> pdf: Add binds for `pdf-history-forward/backward`

- evil-collection.el
- modes/crdt/evil-collection-crdt.el
Adds normal state bindings for [crdt.el](https://code.librehq.com/qhong/crdt.el)'s menu modes. These modes have default bindings which work as expected when in insert state, but not in normal state. This PR adds bindings that add expected functionality while in normal state, which is these menu buffers' default. The `RET` bindings in particular are very helpful; the others are mostly icing on the cake.
https://code.librehq.com/qhong/crdt.el
Assume you're working on `crdt` mode:
> Add bindings for crdt.el's menu modes

- modes/eglot/evil-collection-eglot.el
This adds a binding to eglot for xref-find-definitions-other-frame
> eglot: add binding for xref-find-definitions-other-frame

- modes/shortdoc/evil-collection-shortdoc.el
Just like help buffers.
Bind `TAB` and `S-TAB` to `forward/backward-button` in shortdoc buffers.
> shortdoc: (S-)?tab to navigate buttons

- evil-collection.el
- modes/company/evil-collection-company.el
- modes/gited/evil-collection-gited.el
These bindings are similar to Dired.
Gited is an interface to manage Git branches and tags in a way similar to Dired.
- Not all of the available commands are bound in `gited-mode-map`, so I did 
not bind all of them for Evil Collection.
- I had to move some commands around to more closely match how Dired is set up.
https://git.savannah.gnu.org/cgit/emacs/elpa.git/?h=externals/gited
> Add support for Gited.

- modes/python/evil-collection-python.el
The yet unreleased Emacs 29 can be compiled with built-in tree sitter support, and includes several variants of programming language major modes which do font-locking via tree-sitter. Usually they end with `...-ts-mode` and are defined in the same elisp package as the original major mode. They have separate keymaps and hooks, so to support them those would also need to be used.
I looked supporting `python-ts-mode` via `evil-collection-python-setup`. Actually, the new `python` package also defines a new `python-base-mode` from which both `python-mode` and `python-ts-mode` inherit. In my personal configuration I therefore just use `python-base-mode-hook`  and `python-base-mode-map`, but this would not be backward compatible to older emacs versions, therefore I suggest just adding to both …
> Support new `python-ts-mode`

- modes/beginend/evil-collection-beginend.el
This is technically required for Lisp files that are not part of core Emacs.
> Add "ext:" to declare-function invocations

- modes/vterm/evil-collection-vterm.el
Currently, pressing the `x` key in normal mode does nothing. I don't know much about `:motion` but AFAIK `evil-delete-char` doesn't exist. Using `evil-forward-char` fixes the issue.
> vterm: fix the `x' key, currently it does nothing

- modes/cider/evil-collection-cider.el
I added keybindings for the "step in" and "show stacktrace" commands,
in normal cider documentation, and the underlined letter in the debugging menu where it shows what key for each command, step-in is i and inspect is p, so I changed inspect's binding from i to p, and gave i to "step in"
> cider debugger keybindings

- modes/vterm/evil-collection-vterm.el
Please see the commit descriptions for more information.
I also submitted a similar patch to deal with mouse clicks.
https://github.com/akermu/emacs-libvterm/pull/657
> vterm: prevent movement below the last prompt line

- evil-collection.el
- modes/color-rg/evil-collection-color-rg.el
Search and refactoring tool based on ripgrep. 
https://github.com/manateelazycat/color-rg
> feat: add color-rg

- evil-collection.el
- modes/lms/evil-collection-lms.el
Follow up on https://github.com/emacs-evil/evil-collection/pull/569
lms.el allows the user to control an instance of Logitech Media Server from Emacs.
https://hg.serna.eu/emacs/lms
> Add support for lms.el

- modes/vertico/evil-collection-vertico.el
> vertico: fix scroll direction of C-u/C-d

- evil-collection.el
Makes it possible to indiscriminately translate multi-key sequences like "gj" without errors. Using plain `lookup-key` will end up binding a bunch of keys to a number like 1 instead of a command, because it returns a number when it's passed an invalid sequence of prefix characters. `evil-lookup-key` discards those numbers and returns nil instead.
For example, based on the documentation, here's what someone (i.e. me) might try if they wanted to use `evil-mode` and `evil-collection` with another keyboard layout.
```emacs-lisp
(defvar evil-colemak-dh-translations
'("n" "j"  "N" "J"
"e" "k"  "E" "K"
"m" "h"  "M" "H"
"i" "l"  "I" "L"
"k" "n"  "K" "N"
"h" "m"  "H" "M"
"u" "i"  "U" "I"
"l" "u"  "L" "U"
"j" "e"  "J" "E"
"gn" "gj"  "gN" "gJ"
"ge" "gk"  "gE" "gK"
"gm" "gh"  "gM" "gH"
"gi" "gl" …
```
> Use evil-lookup-key when translating keys

- modes/minibuffer/evil-collection-minibuffer.el
`evil-collection-minibuffer-maps` is defined but not replaced in `evil-collection-minibuffer-setup`.
> minibuffer: fix typo

- modes/docker/evil-collection-docker.el
This add support for `docker-context-*` commands in `evil-collection-docker.el`.
Commands added in https://github.com/Silex/docker.el/commit/bd8f189b445a3ae7f539fac00e98627f76aaa8e2
> evil-collection-docker.el: add 'docker-context-*' bindings

- modes/ement/evil-collection-ement.el
I noticed this typo in the new ement.el module just after it got merged.  I apologize for not actually looking at the code at the time I commented on the PR!
> Fix typo in ement.el

- modes/mu4e/evil-collection-mu4e-1.8.el
- modes/mu4e/evil-collection-mu4e.el
Commit https://github.com/djcb/mu/commit/a4707afe1218330eb5bd0a6cc0b2984844643d7e (even before mu 1.8.0) changed the name of `mu4e~main-toggle-mail-sending-mode` function to `mu4e--main-toggle-mail-sending-mode`. That caused my configuration to throw:
```
error in process filter: mu4e-error: [mu4e] No binding for mu4e--main-toggle-mail-sending-mode
```
I've renamed that function and everything works now.
> mu4e: fix mu4e--main-toggle-main-sending-mode function name

- modes/elpaca/evil-collection-elpaca.el
elpaca-ui-mark-install has been replaced upstream by elpaca-ui-mark-try.
> evil-collection-elpaca-setup: update command name

- modes/lua-mode/evil-collection-lua-mode.el
- modes/python/evil-collection-python.el
- modes/ruby-mode/evil-collection-ruby-mode.el
- modes/sh-script/evil-collection-sh-script.el
- modes/typescript-mode/evil-collection-typescript-mode.el
- modes/yaml-mode/evil-collection-yaml-mode.el
Since commit https://github.com/emacs-evil/evil/commit/b27997b693dca40a08bfea00ae961f10bf839c0c, `evil-shift-width` is no longer buffer-local by default.
So with current versions of `evil` and `evil-collection`, this leads to inconsistent `evil-shift-width` value in some cases. For example:
- open a YAML file (`evil-shift-width` is globally set to `yaml-indent-offset` ; 2 by default)
- then open a Python file (`evil-shift-width` is now globally set to `python-indent-offset` ; 4 by default)
- switch back to the YAML buffer: the global value of `evil-shift-width` is used (here 4) so the shifting operators (> and <) don't work as expected
This PR fix the problem for all modes that set `evil-shift-value`.
> Set local-buffer value for evil-shift-width

- modes/mu4e/evil-collection-mu4e-1.8.el
- modes/mu4e/evil-collection-mu4e.el
Hi,
In the headers-view of mu4e, the action functions  "mu4e-headers-mark-for-X" can work on selections. This allows to select many emails fast, and mark them with one key.
I've written a patch to make these actions work in evil visual mode.
Regards,
Nicolas
> mu4e: add support for visual actions in header view

- modes/embark/evil-collection-embark.el
it removes non-existing (possibly deprecated) commands and fixes the keybinding for `embark-select` - toggle candidate selection in embark-collect buffer
https://github.com/oantolin/embark
> embark: removes non-existing commands

- modes/cider/evil-collection-cider.el
I just added one keybinding "C" for "Continue without stopping for all breakpoints", consistent with the standard emacs keybindings documented by [cider](https://docs.cider.mx/cider/debugging/debugger.html), and with evil-collections existing cider-debug keybindings (lowercase "c" is already continue until the next breakpoint). Just adding capital "C" so it matches cider: "c" for continue till next breakpoint, "C" for continue without any more breakpoints, leaving the debugger
> all continue-all in cider-debug mode

- evil-collection.el
EDIT: This PR now fully reverts the problematic commit, while adding some glue to make CI green.
This solution is incomplete, and might still fail because of the
impossibility to expand the hook-name dynamically, see the
discussion/screenshots in the PR
Try to address the issues in #750
> Fix: Revert de0b62b604e87ce43e2adc9e09bcd5174e8b877a (evil-with-delay change)

- modes/diff-hl/evil-collection-diff-hl.el
Issue: evil keybinding doesn't work with diff-hl popup
> diff-hl: fix name incompatible

- modes/mu4e/evil-collection-mu4e.el
mu4e-headers-toggle-property replaced the following three toggle
commands (which are now aliases for the new command) in v1.9.5. It
provides its own menu with a key binding for each property, so bind it
to a one-key binding.
The obsolete command bindings are not removed because mu4e is typically
installed with mu via the system package manager and is therefore harder
to upgrade than a typical Emacs package. mu4e-headers-toggle-property
was also renamed to mu4e-search-toggle-property in 1.9.11, but the old
name (which remains as an alias) is preferred for the same reason.
-------
> mu4e: add mu4e-headers-toggle-property

- evil-collection.el
- modes/bufler/evil-collection-bufler.el
A ibuffer and buffer-list alternative.
https://github.com/alphapapa/bufler.el
> bufler: init

- modes/cider/evil-collection-cider.el
This is not a new package, just additions to `cider--debug-mode-map`'s map
Matches cider's existing keybindings on `cider--debug-mode-map`
Since it's already not intentionally ordered (e.g alphabetical),
matching upstream's order helps when eyeballing additions.
Thank you for evil collection 🥳!
> feat(cider): add force-out, inspect-prompt, trace 

- modes/corfu/evil-collection-corfu.el
This PR fixes this issue reported in `corfu`'s repository:
https://github.com/minad/corfu/issues/403
It is caused by a change of signature of the `corfu--setup` function, causing the advice defined by `evil-collection-corfu` to call the advised function with the wrong number of arguments.
This PR fixes this while staying backward compatible with the previous `corfu--setup` signature.
> Fix the new `corfu--setup` signature (backward compatible)

- modes/corfu/evil-collection-corfu.el
A new commit in `corfu` changes the signature of `corfu--teardown`, this PR fixes that.
- https://github.com/minad/corfu/commit/61a20a50369de2cae77d649269d3c047fbbc27ec
- https://github.com/emacs-evil/evil-collection/pull/767#issuecomment-1875366132
> Fix `corfu--teardown` signature (backward compatible)

- modes/pdf/evil-collection-pdf.el
Unless intended, `evil-want-C-d-scroll` should not imply a `C-u` scroll binding
> Pdf: Fix typo

- modes/corfu/evil-collection-corfu.el
Corfu uses the emacs definition of scroll-up (moving the text down) which is inverted to what vim uses.
Fixes #778
> Fix corfu-scroll-up/-down being inverted

- modes/vterm/evil-collection-vterm.el
`evil-collection-vterm-append` doesn't work, and `evil-collection-vterm-append-line` doesn't correctly display where the cursor is located. This fixes both issues.
The **problem** with both commands lies in the fact that `evil-append` **doesn't accurately place the insert-mode cursor in front of the cursor displayed in normal-mode**; instead acting in a functionally identical way as `evil-insert`, but moving only the displayed cursor forward one character until a character is placed.
Moving the cursor forward one character before entering insert mode solves `evil-collection-vterm-append`'s issues. I haven't encountered any unexpected behaviour  with the edge-case scenario of moving the cursor forward at the end of a line, which is the only situation I thought might be problematic with …
> vterm: Visual consistency for append

- modes/corfu/evil-collection-corfu.el
Corfu already binds up/down in emacs state, but not in insert state. Normally this is not a problem, but when using corfu in comint-mode like with chatgpt-shell, up/down moves in the history instead of moving in the corfu completions.
> corfu: bind up/down in insert state

- modes/mu4e/evil-collection-mu4e.el
The commands `mu4e-compose-begin` and `mu4e-compose-end` were removed in commit
https://github.com/djcb/mu/commit/85bfe763362b95935a3967f6585e14b3f9890a70 of version 1.12.0 of mu.  This commit re-adds these commands to the evil collection for mu4e.
> mu4e: re-add removed mu4e-compose-begin/end-commands

- modes/mu4e/evil-collection-mu4e.el
This commit adds a few commands to the mu4e-thread-mode-map. The purpose is to bind these commads to the normal state map so that they don't get overridden by motion state commands.
> mu4e: add thread-mode commands

- modes/magit-todos/evil-collection-magit-todos.el
Currently only "j" is unbound. So we can use it to go down a line in magit-todos section. But "k" can't be used to go up.
> magit-todos: unbind "k" in *-section-map

- modes/mu4e/evil-collection-mu4e.el
These bindings were recently re-added to mu4e in 1.12.2 so we don't need to define them ourselves anymore for that version and later.
> mu4e: update the version check for mu4e-compose-goto-*

- evil-collection.el
- modes/mpdired/evil-collection-mpdired.el
https://elpa.gnu.org/packages/mpdired.html
> Add mpdired

- modes/pdf/evil-collection-pdf.el
Evil users expect to be able to yank to named registers, but pdf-view only gives us `pdf-view-kill-ring-save'. So we implement our own version of evil-yank for pdf-view buffers.
> pdf: implement evil yank to registers

- modes/pdf/evil-collection-pdf.el
Evil's visual-mode does not know how to select text within a PDF, and instead selects the entire pdf image, which is useless and counterintuitive - see doomemacs/doomemacs#6286, emacs-evil/evil-collection#683. Instead, rely on pdf-view to handle the region.
> pdf: disable visual-mode

- modes/corfu/evil-collection-corfu.el
This allows `corfu` popup only shows up while we're in a insertable state.
> fix: show corfu popup when in insertable state

- modes/corfu/evil-collection-corfu.el
Support for `evil-repeat` with Corfu.
See:
https://github.com/minad/corfu/pull/169
https://github.com/minad/corfu/pull/225
> Corfu: evil-repeat support

- modes/corfu/evil-collection-corfu.el
This fixes #801. Basically, we do not usually enable `evil-mode` in the minibuffer so we should allow Corfu to work when the current `evil-state` is `nil`.
> corfu: allow corfu to be used when evil is disabled

- .github/workflows/build.yaml
- .gitignore
- Eask
- Makefile
- evil-collection.el
- modes/magit/evil-collection-magit.el
- modes/mu4e/evil-collection-mu4e.el
Cask is deprecated and doesn't support Windows. [Eask](https://github.com/emacs-eask/cli) is the new replacement for Cask.
This patch does the following:
1. Add test for macOS and Windows
2. Clean up most `Makefile` logic to Eask-file
> ci: Use Eask to test macos and windows

- modes/mu4e/evil-collection-mu4e.el
Before mu4e-1.7.0, using SHR to render HTML emails in mu4e-view-mode was an option. This was removed in mu4e-1.7.0, and mu4e-view-mode now uses Gnus to render HTML emails. This change broke Evil Collection's tab navigation in mu4e-view-mode.
> mu4e: fix broken tab navigation in mu4e-view-mode

- evil-collection.el
- modes/kmacro/evil-collection-kmacro.el
Initial support
The builtin kmacro.
> kmacro: initial support

- evil-collection.el
- modes/eat/evil-collection-eat.el
This package provides `evil-mode` keybindings for the `eat` terminal emulator:
https://codeberg.org/akib/emacs-eat/
> Add support for Eat (Terminal Emulator)

- modes/mu4e/evil-collection-mu4e.el
`mu4e-message-kill-buffer` was replaced with `message-kill-buffer` in mu4e `1.12.*` at 
https://github.com/djcb/mu/commit/20878c872576b2711d43711194f3db0bc86566f4 
This commit replace specific functions with `mu4e-user-agent` properties to make it work for both versions.
> Replace specific functions with `mu4e-user-agent` properties

- modes/mpdired/evil-collection-mpdired.el
> Update mpdired keybinding to the new funtions

- evil-collection.el
- modes/magit-repos/evil-collection-magit-repos.el
- modes/magit/evil-collection-magit.el
The fix for https://github.com/emacs-evil/evil-collection/issues/637 reintroduced the problem reported in https://github.com/emacs-evil/evil-collection/issues/510.
This PR extracts magit-repos bindings from magit mode by creating a new separate mode. This should make possible to load correctly magit-repos bindings without interfering with magit main bindings loading process.
> magit: Separate mode for magit-repos

- modes/notmuch/evil-collection-notmuch.el
In the previous version, pressing "RET" (i.e., calling `evil-collection-notmuch-hello-ret`) on a recent searches to enter a search mode buffer, then pressing `q` to quit the search buffer and return to the hello buffer, would result in all evil state keybindings in `notmuch-hello-mode-map` being deactivated. Rewriting the `evil-collection-notmuch-hello-ret` function resolves this issue.
> notmuch: fix `RET` keybinding in `notmuch-hello-mode`.

- modes/gnus/evil-collection-gnus.el
**Function**: `gnus-group-next-group`, `gnus-group-prev-group`
**Default binding**: 'N', 'P'
**Proposed binding**: 'C-j', 'C-k'
**Rationale**: These same bindings, 'C-j'  and 'C-k', already exist for similar movements in `gnus-summary-mode-map` and  in other modes such as  org and magit . This addition makes the Gnus bindings more consistent within Gnus modes and across other modes/maps in the package. It also prevents users from accidentally removing a topic with default 'C-k' (gnus-topic-kill-group) while expecting to perform an evil movement action.
> Gnus: fix gnus-group next and prev inconsistency

- README.org
Just found broken url. You can commit it yourself and discard the PR, so that I don't get on the list of contributors. I am okey with it. I don't want to be in the list because nothing special / or functional in this pr.
> Fix link to Doom Emacs reference (another readme update PR, sorry)

- modes/gnus/evil-collection-gnus.el
**Function**: gnus-summary-browse-url
**Default binding**: 'w'
**Proposed binding**: 'gX'
**Rationale**: This same Vim-like binding already exists in the package, but only for the article-mode/map. This addition enables a more dynamic workflow allowing users to open articles' URLs directly from summary-mode, as  ̶G̶o̶d̶ ̶i̶n̶t̶e̶n̶d̶e̶d̶ the function name describes.
_For the record, I personally have overridden this and other bindings in this module to match the Gnus defaults in my configuration, some of them create less friction IMO. However, I believe I will eventually get used to the choices made by the collection, coming from a Gnus/Emacs defaults background. The more I learn Vim and consider the collections' changes/choices for Gnus, the more they make sense :smile:  (Anyways, I …
> Gnus: add gnus-summary-browse-url binding

- modes/magit/evil-collection-magit.el
`evil-collection-magit-toggle-text-mode` currently doesn't work in `git-rebase-mode` buffers, as the `cond` checks only for `'magit-mode`. Thus the function just shows the error "evil-collection-magit-toggle-text-mode unexpected state" if invoked in a `git-rebase-mode` buffer. The `C-t` and `\` bindings are also not set while in this mode.
These changes make `evil-collection-magit-toggle-text-mode` also work in `git-rebase-mode`, and set up the same key bindings in this mode. Because `git-rebase-mode` also enables `read-only-mode` in the buffer, we need to disable that too when switching to `text-mode`.
> Make magit-toggle-text-mode work in git-rebase-mode buffers

- evil-collection.el
- modes/dape/evil-collection-dape.el
Dape is an debug adapter client for emacs, like lsp but for debugging.
https://github.com/svaante/dape
> dape: Add initial support

- modes/view/evil-collection-view.el
view-mode itself recommends using this function to quit the mode in
in a message in its source code:
```
View mode: type \\[help-command] for help, \\[describe-mode] for commands, \\[View-quit] to quit.
```
Using `#'quit-window` does not work as expected when viewing a diff using view-mode for a buffer in a save prompt in magit: `#'quit-window` breaks the prompting sequence, whilst `#'View-quit` doesn't.
> fix(view-mode): use `#'View-quit`

- modes/org/evil-collection-org.el
A [GNU Emacs](https://www.gnu.org/software/emacs/) major mode for keeping notes, authoring documents, computational notebooks, literate programming, maintaining to-do lists, planning projects, and more — in a fast and effective plain text system.
https://orgmode.org/
When selecting a date in org mode (e.g. using C-c .), by default you select dates using Shift+Arrow keys.
This change will allow you to use M-hjkl/HJKL to move by day, week, month and year directly from the minibuffer.
I did the rebinding with `org-defkey` insted of `evil-collection-define-key` - for some reason, the former works while the latter does not. Let me know if there is a better way.
Closes #816
> Org: Date movement for calendar date selection in minibuffer

- modes/dired/evil-collection-dired.el
The next Emacs release will come with a new command: `dired-do-open`.
This PR just adds a keybinding for this command in evil `normal` state (same as defined in `emacs` state).
Dired is a built-in package.
Link to the new command in NEWS file : https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS?h=emacs-30#n1092
> dired: add keybinding for dired-do-open

- modes/vlf/evil-collection-vlf.el
Confusingly, [`vlf-mode-map` and `vlf-prefix-map`](https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=blob;f=vlf.el;h=ae918e0309af045dec9d9838f63437237d24cbc5;hb=refs/heads/externals/vlf#l79) are the opposite of what they sound like, so to apply the keybindings without a prefix, they need to go in `vlf-prefix-map`.
`evil-normalize-keymaps` seems to also be needed for the keybindings to work.
> vlf: fix keybindings

- modes/mu4e/evil-collection-mu4e.el
mu4e-search-query was introduced in mu4e v1.12.0
bindings are added for the main and headers view
> mu4e: add 'c' binding to mu4e-search-query

- modes/emms/evil-collection-emms.el
`emms-browser-delete-files` is defined as an identical alias of `emms-browser-remove-tracks`, and the former is disabled by default.
The interactive functionality of the two is:
- without prefix argument, only removes tracks from the browser view and clean the cache respectively
- with prefix argument, delete the file too
So it makes more sense to use `emms-browser-remove-tracks` instead, as its name matches its default behavior and also is not disabled.
> emms: Replace emms-browser-delete-files with non-disabled alias

- modes/dashboard/evil-collection-dashboard.el
Arguments expected by 
`dashboard-insert-startupify-lists` have recently changed (see https://github.com/emacs-dashboard/emacs-dashboard/commit/2be75c0ab87a6279ea9840f7c043f7605788d6fb).
So `evil-collection-dashboard-setup-jump-commands` must be adapted accordingly.
> Dashboard: fix function arguments for advice

- modes/telega/evil-collection-telega.el
`bury-buffer` does not close Telega's chat window, use `quit-window` instead.
N/A
https://github.com/zevlg/telega.el/blob/b32bf17d8f3745a69cb808f684881596de592ee5/telega-chat.el#L1659
> telega: close chat with quit-window

- modes/mpc/evil-collection-mpc.el
Wrap some keybindings in kbd for fixing and add more.
this one is emacs builtin.
> mpc: add more keybindings and fix original kbd format

- modes/slime/evil-collection-slime.el
Fix the binding of `goto reference` in `slime mode`.
The command `slime-who-references` **is not the proper command** to find the references **on a symbol**.
Actually, the `slime-who-references` only works on **global variables**, it doesn't works for **functions**, **methods** and **class**.
As documented:
```
slime-who-references is an interactive byte-compiled Lisp function in
‘slime.el’.
It is bound to g r, <normal-state> g r, C-c C-w C-r and C-c C-w r.
(slime-who-references SYMBOL)
Show all known referrers of the global variable SYMBOL.
[back]
```
The command `slime-edit-uses` is an all-in-one command, that does combines all the commands to find the references **on a symbol**, including: `a variable`, `a function`, `a method`, `a class`, `a specializer`.
As documented:
``` …
```
> fix: the goto-reference in slime-mode only works for global variables.

- evil-collection.el
- modes/ultra-scroll/evil-collection-ultra-scroll.el
`ultra-scroll` provides significantly improved smooth scrolling over the built-in `pixel-scroll-precision-mode`. It can also hide the cursor, disable `hl-line`, etc. when scrolling. Unfortunately, the "hide cursor" feature doesn't work with Evil because Evil constantly resets the cursor depending on the current state.
This integration hides the cursors for both `motion` and `normal` state when scrolling with `ultra-scroll`.
https://github.com/jdtsmith/ultra-scroll
> Add ultra-scroll

- evil-collection.el
- modes/minesweeper/evil-collection-minesweeper.el
Minesweeper game!
https://github.com/calancha/Minesweeper
> Add minesweeper

- modes/mu4e/evil-collection-mu4e.el
This reverts commit 05731c551be8cdda40ae6479adfb30b7e9c7fe39.
This fixes an issue that arises when loading `evil-collection-mu4e`, which gives:
```
Key sequence c c starts with non-prefix key c
```
This occurs for both `mu4e-headers-mode-map` and `mu4e-main-mode-map`.
This should probably just be a different key, but for now I'm just trying to get it unbroken.
cc @RyanGibb for visibility.
Thanks for the wonderful library!
> fix prefix key collision for mu4e

- modes/compile/evil-collection-compile.el
> Add M-RET binding for compilation mode

- evil-collection.el
- modes/reader/evil-collection-reader.el
An alternative document reader which utilizes the magic of MuPDF to quickly and beautifully display the contents of those documents inside Emacs.
https://codeberg.org/divyaranjan/emacs-reader
> reader: Initial support

- evil-collection.el
- modes/hideshow/evil-collection-hideshow.el
- modes/hs-minor-mode/evil-collection-hs-minor-mode.el
hideshow is the built in minor mode for selective display.
See: https://www.gnu.org/software/emacs/manual/html_node/emacs/Hideshow.html
> added shortcut "z L" for hs-minor-mode function "hs-hide-level"

- evil-collection.el
- modes/difftastic/evil-collection-difftastic.el
`difftastic` is a special major mode similar to diff-mode, which integrates the command line tool with the same name.
https://github.com/pkryger/difftastic.el
> Add difftastic
