- evil-collection-util.el
- evil-company.el
- evil-debbugs.el
- evil-edebug.el
- evil-elisp-mode.el
- evil-emms.el
- evil-evilified-state.el
- evil-pdf.el
Now it cleanly byte compiles :)
> Byte compilation (again)

- evil-company.el
> Make company-tng optional

- evil-collection-minibuffer.el
> Fix updated prefix in minibuffer-setup-hook

- evil-collection-minibuffer.el
- evil-collection.el
- readme.org
`evil-collection-minibuffer-init` had to be renamed as well. You could add an alias if you want to remain backward compatible.
>  Handle ivy in minibuffer and add a defcustom to enable minibuffer

- evil-collection-ag.el
- evil-collection-compile.el
- evil-collection-evil-search.el
- evil-collection-info.el
@dieggsy @Ambrevar @noctuid
Would appreciate a quick look if you got time.
> Support evil-search-module set to evil-search (#49)

- readme.org
correctly set `evil-want-integration` to `nil`
> Add missing setq in `use-package` snippet

- evil-collection-reftex.el
- evil-collection.el
I created this config that support some reftex functionality. Some keybindings could use some evilification, also changed the default prompts from reftex to show these changes with the exception of the promt from reftex-toc.
> Add reftex

- evil-collection-buff-menu.el
- Question: should this go in motion or normal state?
- If a key is already binded correctly I should put it anyways?
- There isn't a `Buffer-menu-unmark-all-buffers` function.
- This works! yey!
- Is "M" a valid unmark key? should I put "#" AND "M"?
> Added some preliminary keys

- evil-collection-vdiff.el
- evil-collection.el
Refs #70
Please let me know if I can improve the PR.
Maybe the `evil-collection-delete-operators` var should be in evil-collection.el
> Add vdiff.el support

- evil-collection-dired.el
- evil-collection-ivy.el
- evil-collection-wdired.el
- evil-collection-wgrep.el
- evil-collection.el
- readme.org
Would appreciate a quick look.
https://github.com/emacs-evil/evil-collection/issues/106
@Ambrevar @noctuid @terlar
> Wdired+wgrep

- evil-collection-ivy.el
- evil-collection-pdf.el
> Ivy escape minibuffer

- evil-collection-ediff.el
- evil-collection.el
Adds evil-collection-ediff.el
Ref #129 
Please check to make sure I followed the conventions of the repo properly.
> Ediff: Merge from evil-ediff.el

- evil-collection-elisp-mode.el
- evil-collection-helm.el
Mostly this fixes unquoted maps in the helm bindings.
> Fix bugs from transition to new define-key

- evil-collection.el
Rename evil-collection-describe-all-bindings to
evil-collection-describe-bindings. By default the function prints all known
evil-collection bindings. With a non-nil interactive argument, print only the
bindings corresponding to active modes in the current buffer.
> Enhance describe bindings functionality.

- evil-collection.el
They all might be filtered by the white and black lists.
> Accept no bindings in evil-collection-define-key

- evil-collection.el
Use better version of the map active check and remove the old one. Don't print
out menu-items and lambdas.
> Improve evil-collection-describe-bindings

- evil-collection-lsp-ui-imenu.el
change the bindings to C-j and C-k to match other mode's bindings
> fix bindings for lsp-ui next-kind and prev-kind

- evil-collection-debbugs.el
@Ambrevar Can you double check these changes look good before merging?
> Debbugs: Tweak

- evil-collection-ebib.el
- evil-collection.el
This is very basic support for ebib, which is a bibliography manager. Comments and additions are welcome
> ebib: Add initial support

- evil-collection-tetris.el
- evil-collection.el
Evil keybindings for tetris mode
(https://www.emacswiki.org/emacs/TetrisMode)
> Add tetris

- evil-collection-omnisharp.el
- evil-collection.el
Add some basic keybindings for omnisharp
> Add omnisharp

- evil-collection-2048-game.el
- evil-collection.el
Evil keybindings for [2048-game](https://bitbucket.org/zck/2048.el/src/ea6c3bce8ac1c17dae5ac711ae4e931c0495e455/)
> Add 2048-game

- evil-collection.el
Like errors related to prefix keys already being defined
> Catch errors in evil-collection-define-key

- Cask
- evil-collection.el
This is not at all ready to be merged (and the package is not on MELPA), but I thought I'd post what I have in case anyone wants to try it out or look at it (I've only tested it with evil-collection's proced keybindings). Issues/problems with the package are listed in the todo.org. I'll post here again once I've finished the readme. I'll also post an example of how tagging/filtering would work (it's possible to filter by the recorded data or by recorded metadata that isn't printed).
[Here](https://github.com/noctuid/annalist.el) is a link to the repo.
> Use annalist for recording/describing keybindings

- readme.org
> Reformat third-party packages in README as table

- modes/outline/evil-collection-outline.el
- readme.org
> Disable <tab>-based bindings by default

- modes/info/evil-collection-info.el
This fixes some of the bugs with Info-mode searching. There is still a problem with search direction when using isearch (rather than evil-search).
> Fix searching in Info-mode

- modes/docker/evil-collection-docker.el
Hello,
Don't merge this yet, it'll be useful once Silex/docker.el#109 is merged.
> Adapt docker.el after transient migration

- evil-collection.el
- modes/tar-mode/evil-collection-tar-mode.el
This PR adds support for the builtin `tar-mode`. I tried to keep it similar to the existing `arc-mode` configuration.
> Add support for tar-mode

- modes/docker/evil-collection-docker.el
> Fix docker bindings

- modes/info/evil-collection-info.el
Discussion [here](https://github.com/emacs-evil/evil-collection/issues/322).
> Add missing keybindings in info mode

- evil-collection.el
- modes/bm/evil-collection-bm.el
> Add bindings for bm mode

- modes/bm/evil-collection-bm.el
Sorry for missing the `noerror` flag
> Fixed require error of bm.el

- evil-collection.el
- modes/auto-package-update/evil-collection-auto-package-update.el
> Add bindings for auto-package-update

- modes/bm/evil-collection-bm.el
> Fixed: Add evil-collection-bm-maps

- modes/mu4e/evil-collection-mu4e.el
> fix insert state activation issue in org-mu4e

- evil-collection.el
- modes/elfeed/evil-collection-elfeed.el
The bindings are stolen from `evil-collection-man.el`
> TAB can move the point to the next link

- evil-collection.el
> Fix: process-menu is defined in simple.el

- modes/unimpaired/evil-collection-unimpaired.el
> unimpaired: support url encode/decode

- evil-collection.el
- modes/calendar/evil-collection-calendar.el
- readme.org
> calendar: Bind Org functions in calendar keymap

- evil-collection.el
- modes/explain-pause-mode/evil-collection-explain-pause-mode.el
https://github.com/lastquestion/explain-pause-mode/
> explain-pause-mode: add evil bindings

- modes/eshell/evil-collection-eshell.el
> Bind eshell-kill-input in Evil insert state

- modes/ggtags/evil-collection-ggtags.el
> ggtags: Make "gk" and "C-k" invoke 'previous-error

- evil-collection.el
- modes/thread/evil-collection-thread.el
- modes/timer-list/evil-collection-timer-list.el
These two modes are similar so I put it all together.
> thread&timer-list: add evil bindings

- modes/dired/evil-collection-dired.el
The binding is borrowed from elfeed
> dired: dired-narrow integration

- evil-collection.el
- modes/zmusic/evil-collection-zmusic.el
See #376 
https://hg.sr.ht/~zck/zmusic
> Add zmusic

- modes/gnus/evil-collection-gnus.el
I did a fancy loop to set all the modes initial state to 'normal, to inhibit insert, and to set up some common bindings. The way I did it might be a little controversial.
Everything else is just little tweaks
> Gnus changes

- modes/bookmark/evil-collection-bookmark.el
Put `global-evil-collection-unimpaired-mode` into a group to make CI happy
> bookmark: {mark,unmark}-all

- modes/unimpaired/evil-collection-unimpaired.el
<kbd>C-u 3 ]b</kbd> can switch to the next 3rd buffer.
> unimpaired: [b and ]b can be called with prefix arg

- evil-collection.el
- modes/calc/evil-collection-calc.el
- modes/dashboard/evil-collection-dashboard.el
- modes/disk-usage/evil-collection-disk-usage.el
- modes/elfeed/evil-collection-elfeed.el
- modes/eww/evil-collection-eww.el
- modes/guix/evil-collection-guix.el
- modes/hackernews/evil-collection-hackernews.el
- modes/help/evil-collection-help.el
- modes/helpful/evil-collection-helpful.el
- modes/info/evil-collection-info.el
- modes/proced/evil-collection-proced.el
- modes/process-menu/evil-collection-process-menu.el
- modes/simple/evil-collection-simple.el
- modes/transmission/evil-collection-transmission.el
- modes/trashed/evil-collection-trashed.el
- modes/youtube-dl/evil-collection-youtube-dl.el
- modes/ztree/evil-collection-ztree.el
- readme.org
Follow guides in #397 
There are tons of bindings to be refined though.
> read-only mode bindings

- modes/unimpaired/evil-collection-unimpaired.el
The implementation is stolen from [here](https://stackoverflow.com/questions/2423834/move-line-region-up-and-down-in-emacs). Maybe it's not in evil style, revising is welcome.
@jojojames @Ambrevar
> unimpaired: exchange line

- evil-collection.el
- modes/consult/evil-collection-consult.el
> consult: Add evil bindings

- modes/notmuch/evil-collection-notmuch.el
I was able to track this change to commit [adfded9ed0a5a4b06886f462314cd4511cb72d47](https://git.notmuchmail.org/git?p=notmuch;a=commit;h=adfded9ed0a5a4b06886f462314cd4511cb72d47).
I am kinda new to elisp, let me know if there are any issues.
Fixes https://github.com/emacs-evil/evil-collection/issues/415
> Update notmuch binds to reflect changes in notmuch

- modes/sly/evil-collection-sly.el
sly-eval-print-last-expression is implemented like this:
```
(defun sly-eval-print-last-expression (string)
"Evaluate sexp before point; print value into the current buffer"
(interactive (list (sly-last-expression)))
(insert "\n")
(sly-eval-print string))
```
Since the arguments are already populated by the time the advice happens,
evaluating something like this:
(+ 1 1[)] ; bracket wrapping cursor representing cursor position.
will evalute to 1 when we expect (+ 1 1) to be evaluated. We advise
`sly-last-expression` with a before advice to move the cursor forward one before
grabbing the sexp.
@nnoodle I see you are a sly connoisseur, if you have some time can you see if this works for you and the solution is palatable (e.g. wouldn't give you a headache to see that -sly-last-expression- …
> Sly: Switch advice to `sly-last-expression`

- modes/mu4e/evil-collection-mu4e.el
Useful functions borrowed from spacemacs
> add keybindings for mu4e-compose-mode

- evil-collection.el
- modes/mpdel/evil-collection-mpdel.el
> mpdel: add evil keybind

- modes/vterm/evil-collection-vterm.el
Draft, still working (and taking requests) on what to add.
@jixiuf All the bindings that depend on delete region don't seem to be working for me. Delete-region itself works, I'm not trying to delete anything outside the editable portion of the current prompt to my knowledge.
> Add additional evil libvterm keybindings

- modes/consult/evil-collection-consult.el
Jump to evil markers in current buffer
> consult-evil-mark

- modes/consult/evil-collection-consult.el
corrected global marker logic in mark ring and updated internal functions.
> internal function & mark ring fix

- evil-collection.el
- modes/telega/evil-collection-telega.el
Here is a problem about keybinds on buttons. Currently, I remove the original keybinds on these button and bind new ones which may be a reasonable solution.
> Add telega keybindings for evil

- modes/emms/evil-collection-emms.el
The fixes the paste commands in emms playlist mode.
> [emms]: fix emms paste command

- modes/consult/evil-collection-consult.el
> fix default mark-ring for evil-collection-consult-mark

- evil-collection.el
- modes/forge/evil-collection-forge.el
- modes/magit/evil-collection-magit.el
https://github.com/emacs-evil/evil-collection/issues/543
> Add support for forge

- modes/mu4e/evil-collection-mu4e.el
> Mu4e: Fix name of command for saving attachments

- modes/unimpaired/evil-collection-unimpaired.el
Use evil-define-motion macro, which sets :motion repeat, set :jump t,
and add support for counts.
> unimpaired: turn functions into proper motions

- modes/evil-mc/evil-collection-evil-mc.el
😄 
Feel free to comment about `g.`
I considered `gc` or `gb` but it's taken in other modes.
> Bind evil-mc-cursors-map to `g.`

- evil-collection.el
> Add mpc to supported-modes

- modes/docker/evil-collection-docker.el
I'm the maintainer of docker.el :wink:
> Update docker bindings according to latest changes

- modes/magit/evil-collection-magit.el
See https://github.com/magit/transient/issues/192.
> Use transient's definition macros by their new names

- modes/magit/evil-collection-magit.el
> magit: fix tests

- modes/embark/evil-collection-embark.el
add more keybindings to embark-collect-mode.
Most of the keybindings are consistent with the embark-collect default and dired.
> enhance embark-collect-mode

- modes/flymake/evil-collection-flymake.el
WIP: I haven't tested these yet.
Testing help appreciated.
> Adds goto next and previous flymake bindings

- modes/minibuffer/evil-collection-minibuffer.el
> minibuffer: cc fix

- modes/ebuku/evil-collection-ebuku.el
* ebuku-copy-title
* ebuku-copy-index
> evil-collection-ebuku: Add bindings for new functions.

- modes/telega/evil-collection-telega.el
Some functions are renamed.
https://github.com/zevlg/telega.el
> Fix telega function names

- modes/tabulated-list/evil-collection-tabulated-list.el
> tabulated-list-mode: add bindings for column navigation

- modes/smerge/README.org
Hi, I added a README.org and keybinding table for smerge-mode.
> smerge: Add keybinding table

- modes/mu4e/evil-collection-mu4e.el
Reverts emacs-evil/evil-collection#655
> Revert "Update mu4e-main Maildirs section"

- modes/mu4e/evil-collection-mu4e.el
Tagging @tshu-w 
Sorry for the mess earlier. I have confirmed that this works with mu4e-maildir-shortcuts set to various values as well as unset.
> mu4e: update mu4e-main Maildirs section

- modes/company/evil-collection-company.el
fixes #664
- [ x ] byte-compiles cleanly
- [ x ] `M-x checkdoc` is happy.
- [ x ] define `evil-collection-mpc-setup` with `defun`
- [ x ] define `evil-collection-mpc-mode-maps` with `defconst`
- [ x ] All functions should start with `evil-collection-mpc-`
> Fix evil clobbering active company-mode keymap

- modes/consult/evil-collection-consult.el
Breaking change to consult--location candidate was introduced with consult 4be224fb1cfa9b983dca84408720a71d112b1e2c. Fixes #703.
> Fix evil-collection-consult-mark

- modes/mu4e/evil-collection-mu4e-1.8.el
- modes/mu4e/evil-collection-mu4e.el
This is the continue of #720 since we want to resolve the byte compiler error.
And I would like to open a new PR at here such that I can directly test if the new commits resolve the byte compiler error.
> Continue of #720: Adapt evil-collection-mu4e for latest mu4e development version

- modes/vterm/evil-collection-vterm.el
> vterm: allow moving the cursor backwards when exiting insert state

- evil-collection.el
This is a PR for addressing #746. I essentially made the code change mychris described in his issue post.
> fix lazy loading of evil-collection-image

- modes/vundo/evil-collection-vundo.el
Adds bindings for the new vundo commands `vundo-diff` (d), `vundo-diff-mark`(m) and `vundo-diff-unmark`(u).
`vundo--debug` was bound to (d), because it's an intern debug function, i changed that binding to (D).
> Add bindings for new vundo diff operations.

- modes/vterm/evil-collection-vterm.el
Implements evil's "replace" operator ("r") for vterm.
> vterm: implement replace

- modes/elpaca/evil-collection-elpaca.el
[This upstream commit](https://github.com/progfolio/elpaca/commit/039ae35a573af904e425b95e1cf0401e3f43537b) has renamed the `-update` commands to `-merge`.
> `evil-collection-elpaca-setup`: `update` -> `merge`

- modes/mu4e/evil-collection-mu4e.el
> mu4e: fix extra quotes in evil-collection-mu4e

- modes/mu4e/evil-collection-mu4e.el
> mu4e: bind mu4e-compose-wide-reply

- modes/pass/evil-collection-pass.el
This form was incorrect, fixing it
> pass: define-function is corrected

- modes/vundo/evil-collection-vundo.el
Bind the new command `vundo-next-root` that was added to vundo recently.
> Bind 'w' to new command vundo-next-root

- modes/mpdired/evil-collection-mpdired.el
Update a keybinding to the new function.
> Update keybindings to new functions

- modes/telega/evil-collection-telega.el
Updating some functions that were replaced in https://github.com/zevlg/telega.el/commit/aa8ebe362e1092a1603afc06e233bace6ce67476
> telega: Replace obsolete functions

- modes/mpc/evil-collection-mpc.el
> remove wrong bindings and add some useful ones in mpc

- modes/gptel/evil-collection-gptel.el
Adding keybindings for `gptel-context-buffer-mode-map`.
> gptel: add gptel-context-buffer-mode-map

- modes/vertico/evil-collection-vertico.el
> Add gg/G bindings for vertico
